name: Update docs
on: 
  workflow_call:
      secrets:
        SSH_GH_PAGES:
          description: 'SSH key for GitHub Pages deployment'
          required: true
      inputs:
        package-dependencies:
            description: 'Apt package dependencies'
            required: false
            default: ''
            type: string

jobs:
  publish-dev-docs:
    name: Publish dev docs
    uses: ./.github/workflows/publish-docs.yml
    secrets: inherit
    concurrency:
      group: dev-docs
      cancel-in-progress: true
    with:
      package-dependencies: ${{ inputs.package-dependencies }}

  publish-release-docs:
    name: Publish release docs
    needs: publish-dev-docs
    uses: ./.github/workflows/publish-docs.yml
    if: always() && startsWith(github.ref, 'refs/tags')
    secrets: inherit
    with:
      version: ${{ github.ref_name }}
      package-dependencies: ${{ inputs.package-dependencies }}

  update-versions:
    name: Update versions.json
    needs: publish-release-docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️ Docs
        uses: actions/checkout@v4
        with:
          repository: unifyai/docs
          ssh-key: ${{ secrets.SSH_GH_PAGES }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Add version to ${{ github.event.repository.name }}.json
        run: |
          python versions/add_version.py ${{ github.event.repository.name }} ${{ github.ref_name }}

      - name: Commit and push
        run: |
          git config --global user.email "ivydl.team@gmail.com"
          git config --global user.name "ivy-seed"
          git add versions/
          git commit -m "Add ${{ github.ref_name }} to ${{ github.event.repository.name }}.json"
          git push
