name: Trigger lint format

on:
  workflow_call:
    secrets:
      IVY_BRANCH_TOKEN:
        required: true
        description: "Token to access ivy-branch account"
    inputs:
      COMMIT_MESSAGE:
        description: "Commit message to prevent re-triggering the workflow"
        required: false
        type: string
        default: "🤖 Lint code"

permissions:
  contents: write

jobs:
  format-code:
    if: ${{ github.event.inputs.COMMIT_MESSAGE != '🤖 Lint code' }}
    runs-on: ubuntu-latest
    name: Trigger lint bot
    steps:
      - name: Execute lint bot
        uses: ./.github/workflows/lint-bot.yml
        with:
          GITHUB_TOKEN: ${{ secrets.IVY_BRANCH_TOKEN }}
